<?php

/**
 * Implements hook_form_alter().
 */
function oep_form_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  
	$form_id_to_edit = array(
    'article_node_form',
  );

  /* Edit for the form */
	if ( in_array($form_id, $form_id_to_edit) ){
  
    $pattern = "/\/node\/[0-9]+\/edit/";
    $action = $form['#action'];
    if ( preg_match($pattern, $action) ) {
      if ( in_array("Editorial Coordinator", $user->roles) ) {
        //re_render_author_form($form, 'edit');
        add_button_author_submit($form);
      } elseif ( in_array("Author", $user->roles) ) {
        re_render_author_form($form, 'edit');
        add_button_author_submit($form);
      }
      
    }

    $arr = array(
      'form' => $form,
      'form_state' => $form_state,
      'form_id' => $form_id,
      'user' => $user,
    );
    dsm($arr, 'oep_form :: hook_form_alter');
	}
}

function re_render_author_form(&$form, $action){
  $fields_to_delete = array(
    'title', 'body',
    'field_authors', 'field_submission_length',
    'field_sources', 'field_deadline', 'field_image',
    'field_tags','field_media','field_editorial_review_group',
    'field_fact_checker','field_copy_editor','field_state',
    'aaa','aaa','aaaa',
    'additional_settings',
    'revision_information',
    'aaaa',
  );
  
  if ( $action == 'edit' ){
    $title = $form['title']['#default_value'];
    
    
    $arr = array_diff($fields_to_delete, array("title", 'body'));
    foreach ( $arr as $value ){
      unset($form[$value]);
    }
    unset($form['actions']['preview']);
    
    $form['title'] = array(
        '#type' => 'markup',
        '#markup' => '<h3><strong>Title</strong></h3>'.$title,
        '#weight' => -5,
    );
  }
}

function add_button_author_submit(&$form){
  
  $form['actions']['change_state_review'] = array(
    '#type' => 'submit',
    '#access' => true,
    '#value' => 'Submit',
    '#weight' => 11,
    '#submit' => array('change_article_state_need_review')
  );
}

function change_article_state_need_review(&$form, &$form_state){
  
  $node = node_form_submit_build_node($form, $form_state);
  $node->field_state['und'][0]['value'] = 'Needs Review';
  //$node->workbench_moderation_state_new = 'needs_review';
  node_save($node);
  
  dsm($node,'Modify here to save article state');
  dsm($form_state,'change_state_review_form_state');
  
  /*
    1. insert into workbench_moderation_node_history values (67,54, 10 , 'needs_review', 'assigned_entry' , 1 , 1346171990 , 0 , 1)
    2. update workbench_moderation_node_history set current = 0 where hid=66;
  */
}