<?php

/**
 * State List: 'in_progress', 'assigned_entry', 'needs_review', 'reviewer_assigned', 'review_completed', 'assigned_revision', 'withdrawn_from_author', 'published'
 */


/**
 * Implements hook_field_widget_form_alter().
 *
 * Adding an autocomplete user input to the node form.
 */
function oep_form_field_widget_form_alter(&$element, &$form_state, $context){
	
}

/**
 * Implements hook_form_alter().
 *
 * Adding an autocomplete user input to the node form.
 */
function oep_form_form_alter(&$form, $form_state, $form_id) {
	
	global $user;
	
	return;
}

/**
 * Implements hook_block_view_alter(&$data, $block)
 */
function oep_form_block_view_alter(&$data, $block){
	
	return;
}

/**
 * Implements hook_comment_view_alter(&$build)
 */
function oep_form_comment_view_alter(&$build){
	
	return;
}

/**
 * Implements hook_contextual_links_view_alter(&$element, $items)
 */
function oep_form_contextual_links_view_alter(&$element, $items){
	
	return;
}

/**
 * hook_entity_view($entity, $type, $view_mode, $langcode)
 */
function oep_form_entity_view($entity, $type, $view_mode, $langcode){
	return;
}

/**
 * hook_entity_view_alter(&$build, $type)
 */
function oep_form_entity_view_alter(&$build, $type){
	return;
}

/**
 * hook_page_build(&$page)
 */
function oep_form_page_build(&$page){
	return;
}
/**
 * hook_page_alter(&$page)
 */
function oep_form_page_alter(&$page){
	global $user;
	return;
}

/**
 * hook_field_attach_delete_revision($entity_type, $entity)
 */
function oep_form_field_attach_delete_revision($entity_type, $entity){
	return;
}

/**
 * hook_field_delete_revision($entity_type, $entity, $field, $instance, $langcode, &$items)
 */
function oep_form_field_delete_revision($entity_type, $entity, $field, $instance, $langcode, &$items){
	return;
}

/**
 * hook_field_storage_delete_revision($entity_type, $entity, $fields)
 */
function oep_form_field_storage_delete_revision($entity_type, $entity, $fields){
	return;
}
/**
 * hook_node_revision_delete($node)
 */
function oep_form_node_revision_delete($node){
	return;
}
/**
 * hook_field_prepare_view($entity_type, $entities, $field, $instances, $langcode, &$items)
 */
function oep_form_field_prepare_view($entity_type, $entities, $field, $instances, $langcode, &$items){
	return;
}





/*
 * Coordinator Role
 */
function oep_coordinator_state_form(&$form, $action, $state){
	
	return;
	
	if ($action == 'add'){
    //unset($form['title']);
    //unset($form['field_authors']);
    //unset($form['field_submission_length']);
    unset($form['field_sources']);
    //unset($form['field_deadline']);
    unset($form['body']);
    //unset($form['field_image']);
		unset($form['field_media']);
		//unset($form['field_tags']);
		unset($form['field_oep_image']);
    
		//unset($form['revision_information']);
    // OR
    //$form['revision_information']['#collapsible'] = false;
    //unset($form['revision_information']['#group']);
    //unset($form['revision_information']['log']);
    //unset($form['options']);
		
    //unset($form['additional_settings']);
		unset($form['comment_settings']);
	}
	
	elseif (($action == 'edit') && in_array($state, array('in_progress', 'assigned_entry')) ){
    /* Unset properties globaly for coordinator*/
    //unset($form['title']);
    //unset($form['field_authors']);
    //unset($form['field_submission_length']);
    //unset($form['field_sources']);
    //unset($form['field_deadline']);
    //unset($form['body']);
    //unset($form['field_image']);
		//unset($form['field_media']);
		unset($form['field_tags']);
		//unset($form['field_oep_image']);
    
		//unset($form['revision_information']);
    // OR
    $form['revision_information']['#collapsible'] = false;
    unset($form['revision_information']['#group']);
    unset($form['revision_information']['log']);
    unset($form['options']);
		
    unset($form['additional_settings']);
		unset($form['comment_settings']);
    
    /** TODO: add current state */
    $nid = $form['#node']->nid;
    $result = db_query('SELECT body_value FROM {field_revision_body} WHERE entity_id = :nid order by revision_id', array(':nid' => $nid));
    $form['state'] = array(
        '#type' => 'markup',
        '#markup' => '<p><b>From State</b> : '. $form['#node']->workbench_moderation['current']->from_state .
        '<br /><b>Current State</b> : '. $form['#node']->workbench_moderation['current']->state. '<p />',
        '#weight' => 4,
    );
    
    /* TODO: Add content of revisions */
    $rnum = 0;
    $revisions_header = '<ul>';
    $revisions_body = '';
    foreach ($result as $row){
      $rnum += 1;
      $revisions[] = $row->body_value;
      $revisions_header .= '<li><a href="#tabs-' . intval($rnum) .'">' . 'revision '. intval($rnum) . '</a></li>';
      $revisions_body .= '<div id="tabs-' . intval($rnum) .'"><p>' . $row->body_value . '</p></div>';
      $revision_content = $row->body_value;
    }
    $revisions_header .= '</ul>';
    $revision_content = '<div class="demo"><div id="tabs">' . $revisions_header . $revisions_body . '</div></div>';
    $form['revisions'] = array(
        '#type' => 'markup',
        '#markup' => '<b>Revisions</b> : <br />'. $revision_content. '<br />',
        //'#markup' => '<b>Revisions</b> : <br />'. $revisions_header . $revisions_body . '<br />',
        '#weight' => 4,
    );
    
	} elseif (($action == 'edit') && in_array($state, array('in_progress', 'assigned_entry')) ){
		
	} elseif ($action == 'admin'){
		
	} else {
		unset($form['title']);
    unset($form['field_authors']);
    unset($form['field_submission_length']);
    unset($form['field_sources']);
    unset($form['field_deadline']);
    unset($form['body']);
    unset($form['field_image']);
		unset($form['field_media']);
		unset($form['field_tags']);
		unset($form['field_oep_image']);
    
		unset($form['revision_information']);
    // OR
    //$form['revision_information']['#collapsible'] = false;
    //unset($form['revision_information']['#group']);
    //unset($form['revision_information']['log']);
    //unset($form['options']);
		
    unset($form['additional_settings']);
		unset($form['comment_settings']);
	}
	
}

/*
 * Author Role
 */
function oep_author_state_form(&$form, $action, $state){
	
	return;
	
	if ($action == 'add'){
		/*
		 * TODO: It shouldn't be reach here
		 */
		unset($form['title']);
    unset($form['field_authors']);
    unset($form['field_submission_length']);
    unset($form['field_sources']);
    unset($form['field_deadline']);
    unset($form['body']);
    unset($form['field_image']);
		unset($form['field_media']);
		unset($form['field_tags']);
		unset($form['field_oep_image']);
    
		unset($form['revision_information']);
    // OR
    //$form['revision_information']['#collapsible'] = false;
    //unset($form['revision_information']['#group']);
    //unset($form['revision_information']['log']);
    //unset($form['options']);
		
    unset($form['additional_settings']);
		unset($form['comment_settings']);
	} elseif (($action == 'edit') && in_array($state, array('in_progress','assigned_entry')) ){
    /* Unset properties globaly for coordinator*/
    unset($form['title']);
    unset($form['field_authors']);
    unset($form['field_submission_length']);
    unset($form['field_sources']);
    
    unset($form['field_deadline']);
    //unset($form['body']);
    unset($form['field_image']);
    unset($form['field_media']);
    unset($form['field_tags']);
    
    //$form['revision_information']['#collapsible'] = false;
    //unset($form['revision_information']['#group']);
    //unset($form['revision_information']['log']);
    //unset($form['options']);
    unset($form['revision_information']);
    //unset($form['additional_settings']);
    
	} elseif ($action == 'admin'){
		
	} else {
    unset($form['title']);
    unset($form['field_authors']);
    unset($form['field_submission_length']);
    unset($form['field_sources']);
    unset($form['field_deadline']);
    unset($form['body']);
    unset($form['field_image']);
		unset($form['field_media']);
		unset($form['field_tags']);
		unset($form['field_oep_image']);
    
		unset($form['revision_information']);
    // OR
    //$form['revision_information']['#collapsible'] = false;
    //unset($form['revision_information']['#group']);
    //unset($form['revision_information']['log']);
    //unset($form['options']);
		
    unset($form['additional_settings']);
		unset($form['comment_settings']);
	}
}

/* TODO: Implement
 * Editor Role
*/
function oep_editor_state_form(&$form, $action, $state){
	
	return;
	/* No add action on Editor */
	if (False && $action == 'add'){

	}

	elseif ( ($action == 'edit') && in_array($state, array('in_progress', 'assigned_entry', 'needs_review', 'reviewer_assigned', 'review_completed', 'assigned_revision', 'withdrawn_from_author', 'published'))){

		unset($form['title']);
		unset($form['field_authors']);
		unset($form['field_submission_length']);
		unset($form['field_sources']);
		unset($form['field_deadline']);
		unset($form['body']);
		unset($form['field_image']);
		unset($form['field_media']);
		unset($form['field_tags']);
		unset($form['field_oep_image']);

		unset($form['revision_information']);
		// OR
		//$form['revision_information']['#collapsible'] = false;
		//unset($form['revision_information']['#group']);
		//unset($form['revision_information']['log']);
		//unset($form['options']);

		unset($form['additional_settings']);
		unset($form['comment_settings']);
	}
}

/* TODO: Implement
 * Managing Editor Role
*/
function oep_managing_editor_state_form(&$form, $action, $state){

	return;
	/* No add action on Editor */
	if (False && $action == 'add'){

	}

	elseif ( ($action == 'edit') && in_array($state, array('in_progress', 'assigned_entry', 'needs_review', 'reviewer_assigned', 'review_completed', 'assigned_revision', 'withdrawn_from_author', 'published'))){

		unset($form['title']);
		unset($form['field_authors']);
		unset($form['field_submission_length']);
		unset($form['field_sources']);
		unset($form['field_deadline']);
		unset($form['body']);
		unset($form['field_image']);
		unset($form['field_media']);
		unset($form['field_tags']);
		unset($form['field_oep_image']);

		unset($form['revision_information']);
		// OR
		//$form['revision_information']['#collapsible'] = false;
		//unset($form['revision_information']['#group']);
		//unset($form['revision_information']['log']);
		//unset($form['options']);

		unset($form['additional_settings']);
		unset($form['comment_settings']);
	}
}

/* TODO: Implement
 * Fact Checker Role
*/
function oep_fact_checker_state_form(&$form, $action, $state){

	return;
	/* No add action on Editor */
	if (False && $action == 'add'){

	}

	elseif ( ($action == 'edit') && in_array($state, array('in_progress', 'assigned_entry', 'needs_review', 'reviewer_assigned', 'review_completed', 'assigned_revision', 'withdrawn_from_author', 'published'))){

		unset($form['title']);
		unset($form['field_authors']);
		unset($form['field_submission_length']);
		unset($form['field_sources']);
		unset($form['field_deadline']);
		unset($form['body']);
		unset($form['field_image']);
		unset($form['field_media']);
		unset($form['field_tags']);
		unset($form['field_oep_image']);

		unset($form['revision_information']);
		// OR
		//$form['revision_information']['#collapsible'] = false;
		//unset($form['revision_information']['#group']);
		//unset($form['revision_information']['log']);
		//unset($form['options']);

		unset($form['additional_settings']);
		unset($form['comment_settings']);
	}
}

/* 
 * TODO: Implement
 * Editor in Chief Role
*/
function oep_editor_in_chief_editor_state_form(&$form, $action, $state){

	return;
	
	/* No add action on Editor */
	if (False && $action == 'add'){

	}

	elseif ( ($action == 'edit') && in_array($state, array('in_progress', 'assigned_entry', 'needs_review', 'reviewer_assigned', 'review_completed', 'assigned_revision', 'withdrawn_from_author', 'published'))){

		unset($form['title']);
		unset($form['field_authors']);
		unset($form['field_submission_length']);
		unset($form['field_sources']);
		unset($form['field_deadline']);
		unset($form['body']);
		unset($form['field_image']);
		unset($form['field_media']);
		unset($form['field_tags']);
		unset($form['field_oep_image']);

		unset($form['revision_information']);
		// OR
		//$form['revision_information']['#collapsible'] = false;
		//unset($form['revision_information']['#group']);
		//unset($form['revision_information']['log']);
		//unset($form['options']);

		unset($form['additional_settings']);
		unset($form['comment_settings']);
	}
}




